### PR TITLE
printf option %{mdatetime} for standard datetime

### PR DESCRIPTION
**Pull request by wilfz**
I suggest a new format option %{mdatetime} to format the modification time in ansi format YYYY-MM-DD hh:nn:ss.
This would ease sorting or importing the output with other programs.
I built it for myself on windows and raspbian and would like to make it available to the public.

### CODE REVIEW

**Comment by Skif-off** [comment]
Check line ending in hash_print.c, please: should be LF, not CRLF.

**Comment by wilfz** [comment]
I changed the line endings. Sorry, didn't see it in my diff tool.

**Comment by rhash** [comment]
Hello, I've just changed %{mtime} format, see 657825709a7711538d9a19120a990ba5120780fb.
But SFV file header will still use the old format.

**Comment by rhash** [comment]
Closing as duplicate of #84.

**Pull request closed without merging**
